### ISSUE TITLE
Running in windows 7

### ISSUE THREAD

**Issue by ChenTsur** [nmellado/Super4PCS#4]
Hello nmellado!

I would like to run super4pcs as part of my research. I have to work on windows 7 due to IT issues. 
What is the list of dependencies required and have you tried it before? is it doable ? 
Where would you recommend to start if my aim is to input two Point Clouds and just receive the transformation between them? 

Chen

**Comment by nmellado** [comment]
Hello ChenTsur,

Thanks for your interest.
I managed to make it work on Windows 10 (7 should be ok) with Visual Studio 2015 (you need it for C++11 support).
Checkout issue #3 for more details (https://github.com/nmellado/Super4PCS/issues/3)
and portWin branch (https://github.com/nmellado/Super4PCS/tree/portWin).
You will need to add cfitsio and libann in the 3rdparty folder.

**Comment by nmellado** [comment]
Windows builds are now supported, check wiki.

**Comment by ChenTsur** [comment]
Hi!
I'm trying to compile the sln . 
Question regarding the 3rd party - which opencv version did you use ?

Chen

**Comment by nmellado** [comment]
Hi,I've used opencv_world310.                                                                                                                                                                                                   For more details, check the following page : ‎https://github.com/nmellado/Super4PCS/wiki/CompilationCheers                                                                                                                                                                                                                De: ChenTsurEnvoyé: samedi 9 avril 2016 19:37À: nmellado/Super4PCSRépondre à: nmellado/Super4PCSCc: Nicolas MelladoObjet: Re: [nmellado/Super4PCS] Running in windows 7 (#4)Hi!
I'm trying to compile the sln . 
Question regarding the 3rd party - which opencv version did you use ?

Chen 

—You are receiving this because you modified the open/close state.Reply to this email directly or view it on GitHub

**Comment by ChenTsur** [comment]
Hi Nicolas!

I've managed to compile Super4pcs sln on windows.

I work with opencv 3.1.0 and with VS 2015.

I've encountered the attached runtime error - please advise me why it could
happen (I tested the attached hippo1 and hippo2 obj).

Thanks ahead!

Chen


[image: תמונה מוטבעת 1]

2016-04-10 0:40 GMT+03:00 Nicolas Mellado <notifications@github.com>:

**Comment by nmellado** [comment]
Hi ChenTsur,

I don't have access to your attached files + images.
Can you send them by email ?

Cheers
